import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,rm,symlink,link} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {gunzipSync} from 'node:zlib';
import {tsImport} from 'tsx/esm/api';
const {packageSource}=await tsImport('../packages/control/source.ts',import.meta.url);
async function fixture(t){const root=await mkdtemp(path.join(tmpdir(),'zenith selected source '));t.after(()=>rm(root,{recursive:true,force:true}));await mkdir(path.join(root,'src'));await writeFile(path.join(root,'index.html'),'<div id="root"></div>');await writeFile(path.join(root,'zenith.app.json'),JSON.stringify({contract:1,name:'Fixture',schema:1}));await writeFile(path.join(root,'src/main.tsx'),'export default function App(){ return <p>Fixture</p>; }');return {root,includes:['index.html','zenith.app.json','src']};}
test('source packaging is byte reproducible, relative and inventory-bound',async t=>{const f=await fixture(t),a=await packageSource(f.root,f.includes),b=await packageSource(f.root,[...f.includes].reverse());assert.deepEqual(a.bytes,b.bytes);assert.equal(a.sha256,b.sha256);assert.equal(a.files.length,3);assert.equal(gunzipSync(a.bytes).includes(Buffer.from('src/main.tsx')),true);assert.ok(a.files.every(v=>!path.isAbsolute(v.path)));});
test('source requires explicit selection and excludes unsupported root inputs',async t=>{const f=await fixture(t);await assert.rejects(packageSource(f.root,[]));for(const file of ['.env','../escape','/absolute','C:\\windows','src/../escape','package-lock.json'])await assert.rejects(packageSource(f.root,[...f.includes,file]));});
test('source refuses unsupported scripts, manifests and secret patterns',async t=>{const f=await fixture(t);await writeFile(path.join(f.root,'package.json'),JSON.stringify({scripts:{build:'curl evil'}}));await assert.rejects(packageSource(f.root,[...f.includes,'package.json']));await writeFile(path.join(f.root,'src/main.tsx'),`const credential='za_${'K'.repeat(43)}';`);await assert.rejects(packageSource(f.root,f.includes),{code:'source_secret'});});
test('source rejects symlink roots, files and hardlinks',{skip:process.platform==='win32'?'Symlink creation needs Windows privileges':false},async t=>{const f=await fixture(t);await symlink(path.join(f.root,'src/main.tsx'),path.join(f.root,'src/linked.tsx'));await assert.rejects(packageSource(f.root,f.includes),{code:'source_symlink'});await rm(path.join(f.root,'src/linked.tsx'));await link(path.join(f.root,'src/main.tsx'),path.join(f.root,'src/hard.tsx'));await assert.rejects(packageSource(f.root,f.includes),{code:'unsafe_source_file'});});
test('source enforces file-size, path-depth and extension bounds',async t=>{const f=await fixture(t);await writeFile(path.join(f.root,'src/large.txt'),Buffer.alloc(2*1024*1024+1));await assert.rejects(packageSource(f.root,f.includes),{code:'unsafe_source_file'});await rm(path.join(f.root,'src/large.txt'));await writeFile(path.join(f.root,'src/runtime.exe'),'unsupported');await assert.rejects(packageSource(f.root,f.includes),{code:'unsupported_source'});await assert.rejects(packageSource(f.root,['src/'+Array(15).fill('folder').join('/')]),{code:'unsafe_source_path'});});
